"""init

Revision ID: 11f4626bb66c
Revises: 
Create Date: 2022-06-12 11:51:52.683177

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '11f4626bb66c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('zones',
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=256), nullable=False),
    sa.Column('comment', sqlmodel.sql.sqltypes.AutoString(length=2048), nullable=True),
    sa.Column('ndviFilename', sqlmodel.sql.sqltypes.AutoString(length=256), nullable=True),
    sa.Column('photoFilename', sqlmodel.sql.sqltypes.AutoString(length=256), nullable=True),
    sa.Column('geoJsonFilename', sqlmodel.sql.sqltypes.AutoString(length=256), nullable=True),
    sa.Column('id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('zones')
    # ### end Alembic commands ###
